<h1>Introduction to NumPy<h1>

In [4]:
import numpy as np

<h2>Creating an array</h2>

In [78]:
arr=np.array([1,2,3,376666645554,5,6,7,8,9])
arr

array([           1,            2,            3, 376666645554,
                  5,            6,            7,            8,
                  9], dtype=int64)

In [77]:
arr.dtype

dtype('int32')

In [7]:
arr.shape

(9,)

In [8]:
arr.dtype

dtype('int32')

In [9]:
arr.ndim

1

In [10]:
arr1=np.array(arr,np.int64)

In [11]:
arr1.dtype

dtype('int64')

In [12]:
arr.ndim

1

In [13]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]],np.int64)

In [14]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int64)

In [15]:
arr2.shape

(3, 3)

In [16]:
arr2.ndim

2

In [17]:
arr2.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [18]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int64)

In [28]:
 arr2.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [20]:
arr=np.arange(10) # creates one dimensional array

In [30]:
arr[8]=20
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7, 20,  9])

In [31]:
arr.dtype

dtype('int32')

In [32]:
arr.shape

(10,)

In [33]:
arr.ndim

1

In [34]:
arr.reshape(2,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7, 20,  9]])

In [35]:
arr.flatten

<function ndarray.flatten>

In [36]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7, 20,  9])

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7, 20,  9])

<h2>Zeros, ones, eye, empty, random,linspace</h2>

In [38]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
ones_array=np.ones((4,7))
ones_array

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [41]:
eye_array=np.eye(3,4,-2) #returns 2-d array , min diagonal=0;upper diagonal >0 ; lower diagonal<0
eye_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [42]:
np.eye(3,3,-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [43]:
np.eye(3,4,7)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
identity_array=np.identity(3) # returns identity array
identity_array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.empty((4,5)) #initial contents are random which depends upon state of the memory

array([[1.30027103e-311, 6.27463370e-322, 0.00000000e+000,
        0.00000000e+000, 1.42413554e-306],
       [5.30276956e+180, 1.02941932e-071, 4.57045791e-071,
        4.05940982e-086, 3.35808809e-143],
       [6.01433264e+175, 6.93885958e+218, 5.56218858e+180,
        3.94356143e+180, 2.68018164e-032],
       [1.29228870e+161, 3.85154859e-057, 1.85586060e-051,
        6.20923496e-144, 1.50008929e+248]])

In [46]:
random_array=np.random.rand(2,5)
random_array

array([[0.91638571, 0.46152972, 0.68417407, 0.13322971, 0.91459244],
       [0.39775767, 0.34826277, 0.06134858, 0.55626072, 0.47991822]])

In [47]:
random=np.random.randint(2,10,size=(2,4))

In [48]:
random

array([[3, 2, 7, 2],
       [8, 7, 5, 9]])

In [80]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

<h2>Difference between ravel and flatten</h2>

In [50]:
arr1=arr.ravel()
arr2=arr.flatten()
print(arr1)
print(arr2)

[ 0  1  2  3  4  5  6  7 20  9]
[ 0  1  2  3  4  5  6  7 20  9]


In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7, 20,  9])

In [52]:
arr[8]=4
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 4, 9])

In [53]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 4, 9])

In [54]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7, 20,  9])

<h2>Python array VS NumPy array</h2>

In [55]:
import sys

In [56]:
py_arr=[1,2,3,4]
num_arr=np.array([1,2,3,4])
print("Space acquired by Python array:",sys.getsizeof(1)*len(py_arr))
print("Space acquired by numpy array :",num_arr.itemsize*num_arr.size)

Space acquired by Python array: 112
Space acquired by numpy array : 16


<h2>vectorization</h2>

In [57]:
import time

In [58]:
num1=np.array([[1,2,3],[6,7,8]])
num2=np.array([[4,5],[6,7],[8,9]])
num3=np.dot(num1,num2)
num=1000000
a=np.random.random(num)
b=np.random.random(num)


In [59]:
start=time.time()
c=np.dot(a,b)
end=time.time()
print(num3)
print("Dot product of two random nymber:",c)
print("Vectorized time:"+str((end-start)*1000)+"ms")

[[ 40  46]
 [130 151]]
Dot product of two random nymber: 250275.41225884325
Vectorized time:2.0155906677246094ms


In [60]:
start=time.time()
c=0
for i in range(num):
    c=c+a[i]*b[i]
end=time.time()
print("Dot product of two random number:",c)
print("Loop time:"+str((end-start)*1000)+"ms")

Dot product of two random number: 250275.41225883097
Loop time:696.0005760192871ms


In [61]:
import timeit

In [62]:
a1 = [np.random.randint(1, 100) for _ in range(1000000)] 
b1 = [np.random.randint(1, 100) for _ in range(1000000)] 
%timeit res = [x * y for x, y in zip(a1, b1)] 


160 ms ± 9.61 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [63]:
a = np.random.randint(1, 100, 1000000) 
b = np.random.randint(1, 100, 1000000) 
%timeit a * b 

4.3 ms ± 196 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
arr

<h2>Boolean Masking</h2>

In [64]:
arr>8

array([False, False, False, False, False, False, False, False, False,
        True])

In [65]:
arr<0

array([False, False, False, False, False, False, False, False, False,
       False])

<h2>Date and Time</h2>

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)